/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.u2a1_joshuawu;
import java.text.DecimalFormat;
/**
 *
 * @author 335181541
 */
public class VehicleProgram extends javax.swing.JFrame {

    /**
     * Creates new form VehicleProgram
     */
    public VehicleProgram() {
        initComponents();
    }

    public static boolean isPositiveDouble(String str) { 
     try {  
        double i = Double.parseDouble(str);
        return (i>0);
     } catch(NumberFormatException e){  
        return false;  
     }  
    }
    public static boolean isPositiveInt(String str) { 
     try {  
        int i = Integer.parseInt(str);  
        return (i>0);
     } catch(NumberFormatException e){  
        return false;  
     }  
    }
    public static boolean isAVehicle(Vehicle a){
        try {
            int i = a.getPassengerNum();
            return true;
        }
        catch (Exception e){
            return false;
        }
    }
    Vehicle vehicles[] = new Vehicle[5];
    int index = 0;
    DecimalFormat df = new DecimalFormat("#0.00");        
            
            
            
            
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleOutput = new javax.swing.JTextArea();
        gasPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        currentGasPrice = new javax.swing.JLabel();
        numPassengers = new javax.swing.JTextField();
        fuel = new javax.swing.JTextField();
        fare = new javax.swing.JTextField();
        passTitle = new javax.swing.JLabel();
        fuelTitle = new javax.swing.JLabel();
        fareTitle = new javax.swing.JLabel();
        createVehicle = new javax.swing.JButton();
        carNum = new javax.swing.JTextField();
        numTitle = new javax.swing.JLabel();
        methods = new javax.swing.JLabel();
        output = new javax.swing.JTextField();
        distTitle = new javax.swing.JLabel();
        distTraveled = new javax.swing.JTextField();
        tripCost = new javax.swing.JButton();
        recallTripCost = new javax.swing.JButton();
        Revenue = new javax.swing.JButton();
        profit = new javax.swing.JButton();
        compareProfits = new javax.swing.JButton();
        secondCarNum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vehicle Program");

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 153, 153));
        title.setText("Vehicle Program");

        vehicleOutput.setEditable(false);
        vehicleOutput.setColumns(20);
        vehicleOutput.setRows(5);
        jScrollPane1.setViewportView(vehicleOutput);

        jButton1.setText("Set Gas Price");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        currentGasPrice.setText("Current Gas Price: not set");

        passTitle.setText("Num of Passengers:");

        fuelTitle.setText("Fuel Efficiency (L/km):");

        fareTitle.setText("Passenger Fare ($):");

        createVehicle.setText("Create Vehicle");
        createVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVehicleActionPerformed(evt);
            }
        });

        carNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carNumActionPerformed(evt);
            }
        });

        numTitle.setText("Vehicle Number:");

        methods.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        methods.setText("Methods");

        distTitle.setText("Distance Traveled (km)");

        distTraveled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distTraveledActionPerformed(evt);
            }
        });

        tripCost.setText("Calculate Trip Cost");
        tripCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripCostActionPerformed(evt);
            }
        });

        recallTripCost.setText("Recall Trip Cost");
        recallTripCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallTripCostActionPerformed(evt);
            }
        });

        Revenue.setText("Revenue");
        Revenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenueActionPerformed(evt);
            }
        });

        profit.setText("Is Profitable?");
        profit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitActionPerformed(evt);
            }
        });

        compareProfits.setText("Compare Profits");
        compareProfits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareProfitsActionPerformed(evt);
            }
        });

        secondCarNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondCarNumActionPerformed(evt);
            }
        });

        jLabel1.setText("Second Vehicle to Compare:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(output, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(currentGasPrice))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(numPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fuelTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(fuel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fare)
                                .addGap(87, 87, 87))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fareTitle)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(gasPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(createVehicle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(methods))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(title)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondCarNum, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(numTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(carNum, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Revenue)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(compareProfits)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profit))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(distTitle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(recallTripCost, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(distTraveled, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tripCost))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentGasPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gasPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passTitle)
                    .addComponent(fareTitle)
                    .addComponent(fuelTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createVehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(methods)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTitle)
                    .addComponent(distTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distTraveled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tripCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recallTripCost)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profit)
                    .addComponent(compareProfits)
                    .addComponent(secondCarNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Revenue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (isPositiveDouble(gasPrice.getText()))
        {
            double gas = Double.parseDouble(gasPrice.getText());
            Vehicle.setGasPrice(gas);
            currentGasPrice.setText("Current Gas Price: " + df.format(gas) + "$");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVehicleActionPerformed
        String str1 = numPassengers.getText();
        String str2 = fuel.getText();
        String str3 = fare.getText();
        if (index < 5)
            if (isPositiveInt(str1) && isPositiveDouble(str2) && isPositiveDouble(str3))
            {
                vehicles[index] = new Vehicle(Integer.parseInt(str1), Double.parseDouble(str3), Double.parseDouble(str2));
                output.setText("Vehicle " + (index+1) + " created");
                vehicleOutput.append("Vehicle " + (index+1) + ":" + vehicles[index].toString() + "\n");
                index++;
            }
            else output.setText("Error in creating vehicle. Please make sure you input the numbers correctly");
        else output.setText("Max number of vehicles reached");
    }//GEN-LAST:event_createVehicleActionPerformed

    private void carNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carNumActionPerformed

    }//GEN-LAST:event_carNumActionPerformed

    private void RevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenueActionPerformed
        String str1 = carNum.getText();
        if (isPositiveInt(str1))
        {
            int num = Integer.parseInt(str1);
            if ((num-1)<index)
            {
                output.setText("Vehicle revenue is " + df.format(vehicles[num-1].revenue()) + "$");                
            }
            else output.setText("Vehicle does not exist");
        }
        else output.setText("Please input a positive integer");  
    }//GEN-LAST:event_RevenueActionPerformed

    private void tripCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripCostActionPerformed
        String str1 = carNum.getText();
        String str2 = distTraveled.getText();
        if (Vehicle.getGasPrice() != -1)
            if (isPositiveInt(str1) && isPositiveInt(str2))
            {
                int num1 = Integer.parseInt(str1);
                int num2 = Integer.parseInt(str2);
                if ((num1-1)<index)
                {
                    output.setText("Trip cost for vehicle " + num1 + " is "  + df.format(vehicles[num1-1].totalCost(num2)) + "$");                
                }
                else output.setText("Vehicle does not exist");
            }
            else output.setText("Please input a positive integer"); 
        else output.setText("Please set the gas price first");
    }//GEN-LAST:event_tripCostActionPerformed

    private void distTraveledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distTraveledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distTraveledActionPerformed

    private void profitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitActionPerformed
        String str1 = carNum.getText();
        if (isPositiveInt(str1))
        {
            int num = Integer.parseInt(str1);
            if ((num-1)<index && vehicles[num-1].getTripCost()!=-1)
            {
                if (vehicles[num-1].isProfitable())
                {
                    output.setText("Vehicle " + num + " will return a profit over 400$.");
                }
                else output.setText("Vehicle " + num + " will NOT return a profit over 400$.");
            }
            else output.setText("Vehicle does not exist or trip cost was not set");
        }
        else output.setText("Please input a positive integer");  
    }//GEN-LAST:event_profitActionPerformed

    private void recallTripCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallTripCostActionPerformed
        String str1 = carNum.getText();
        if (isPositiveInt(str1))
        {
            int num = Integer.parseInt(str1);
            if ((num-1)<index && vehicles[num-1].getTripCost()!=-1)
            {
                output.setText("Trip cost for vehicle " + num + " is " + df.format(vehicles[num-1].getTripCost()) + "$");
            }
            else output.setText("Vehicle does not exist or trip cost was not set");
        }
        else output.setText("Please input a positive integer");          
    }//GEN-LAST:event_recallTripCostActionPerformed

    private void compareProfitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareProfitsActionPerformed
        String str1 = carNum.getText();
        String str2 = secondCarNum.getText();
        String str3 = distTraveled.getText();
        if (isPositiveInt(str1) && isPositiveInt(str2) && isPositiveInt(str3))
        {
            try {
                int num1 = Integer.parseInt(str1);
                int num2 = Integer.parseInt(str2);
                int num3 = Integer.parseInt(str3);
                /*if (vehicles[num1-1].getTripCost()==-1 || vehicles[num2-1].getTripCost()==-1)
                    output.setText("Please calculate the vehicle's trip cost first");
                else */if (Vehicle.compareTo(vehicles[num1-1], vehicles[num2-1], num3))
                    output.setText("Vehicle " + num1 + " has a higher profit");
                else output.setText("Vehicle " + num2 + " has a higher profit");
            }
            catch (ArrayIndexOutOfBoundsException | NullPointerException e){
                output.setText("One or both of the vehicles do not exist. Please make sure you put the correct info.");
            }
        }
        else output.setText("Please input a positive integer for the vehicle numbers and distance traveled.");
    }//GEN-LAST:event_compareProfitsActionPerformed

    private void secondCarNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondCarNumActionPerformed

    }//GEN-LAST:event_secondCarNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Revenue;
    private javax.swing.JTextField carNum;
    private javax.swing.JButton compareProfits;
    private javax.swing.JButton createVehicle;
    private javax.swing.JLabel currentGasPrice;
    private javax.swing.JLabel distTitle;
    private javax.swing.JTextField distTraveled;
    private javax.swing.JTextField fare;
    private javax.swing.JLabel fareTitle;
    private javax.swing.JTextField fuel;
    private javax.swing.JLabel fuelTitle;
    private javax.swing.JTextField gasPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel methods;
    private javax.swing.JTextField numPassengers;
    private javax.swing.JLabel numTitle;
    private javax.swing.JTextField output;
    private javax.swing.JLabel passTitle;
    private javax.swing.JButton profit;
    private javax.swing.JButton recallTripCost;
    private javax.swing.JTextField secondCarNum;
    private javax.swing.JLabel title;
    private javax.swing.JButton tripCost;
    private javax.swing.JTextArea vehicleOutput;
    // End of variables declaration//GEN-END:variables
}
